### ISSUE TITLE
analytics-api failing for docker version

### ISSUE THREAD

**Issue by aniruddhamonker** [aniruddhamonker/contrail-introspect-scrapper#4]
/ # contrail-scrape --analytics-api 10.219.95.55
                                                   Exception in thread Thread-2:
Traceback (most recent call last)::03,  8.90uves/s]
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/ContrailScrape/analytics_uves.py", line 29, in get_api_nodes
    api_response_json = json.loads(api_response_txt)
  File "/usr/local/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

**Comment by aniruddhamonker** [comment]
`[
{
href: "http://x.x.x.x:8081/analytics/uves",
name: "uves"
},
{
href: "http://x.x.x.x:8081/analytics/uve-types",
name: "uve-types"
},
{
href: "http://x.x.x.x:8081/analytics/tables",
name: "tables"
},
{
href: "http://x.x.x.x:8081/analytics/queries",
name: "queries"
}
]`
 
"http://x.x.x.x:8081/analytics/alarms" module is missing on this cluster. 
handled the exception to fix the issue
